version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=dcblog
      - DB_PASS=pass
      - DB_NAME=dcblog
      - JWT_SECRET=jwt_secret
      - ENV=dev
  db:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: dcblog
      MYSQL_USER: dcblog
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
